Initial implementation of converting flow rate to volume for metrics
HydrologicEngineeringCenter/FIRO_TSEnsembles pull request #164
Opened 2023-05-18 01:07 UTC by dvdhoz

Adding methods for computing a volume from a rate for MaxAccumDuration, CumulativeComputable, and Total

2023-05-18 01:10 UTC, dvdhoz commented
I had to update a few of the tests so they are comparing volumes instead of flow rates

2023-05-19 20:54 UTC, Brennan1994 requested changes

2023-05-19 20:54 UTC, Brennan1994 commented on FIRO_TSEnsembles/src/main/java/hec/ensemble/stats/MedianComputable.java
> +            outputUnit = DEFAULT_INPUT_UNITS;
This is weird to me. Why does getInputUnits set output unit and not return anything? potential copy paste error going on her?

2023-05-19 20:54 UTC, Brennan1994 commented on FIRO_TSEnsembles/src/main/java/hec/ensemble/stats/MinComputable.java
> +            outputUnit = DEFAULT_INPUT_UNITS;
same comment. This seems weird

2023-05-19 20:54 UTC, Brennan1994 commented on FIRO_TSEnsembles/src/main/java/hec/ensemble/stats/PercentilesComputable.java
> +            outputUnits = DEFAULT_INPUT_UNITS;
Ok, this is my primary gripe. Lets talk about this

2023-05-23 17:50 UTC, Brennan1994 approved these changes

2023-05-23 17:59 UTC, merged