2400 hour hecTime to ZoneDateTime
HydrologicEngineeringCenter/FIRO_TSEnsembles pull request #232
Opened 2024-01-08 21:58 UTC by dvdhoz

Update how 2400 times are handled when converting from hecTime to ZoneDateTime. Instead of adding 1 to the day and setting the hour to 00:00, converted the hecTime to a String that can be parsed by ZoneDateTime and used the plusDays method in ZoneDateTime to increase the day.  

Fixes #231

2024-01-08 22:36 UTC, ktarbet requested changes
It would be great to add a simple test that reproduces the bug and fix.
Or perhaps tweak existing test.


If you start from scratch it might start looking like this... 
```java

 TimeSeriesCollectionContainer tscc = new TimeSeriesCollectionContainer();
        TimeSeriesContainer tsc = new TimeSeriesContainer();

        HecTime t = new HecTime("01Jan2023","24:00");
        HecTime t2 = new HecTime("01Jan2024","24:00");
        HecTimeArray times = new HecTimeArray();
        times.set(new int[]{t.value(),t2.value()});
        tsc.set(new double[]{1,2,3},times);
        
        tscc.add(tsc);

       DssDatabase db = new DssDatabase(...)
      

```

2024-01-08 22:39 UTC, ktarbet commented
If you pull that functionality out into a HecTimeToZonedDateTime()   then the test will be simple

2024-01-09 22:43 UTC, dvdhoz commented
Added tests to DssDatabase for checking 2400 time periods.

2024-01-09 23:51 UTC, ktarbet approved these changes

2024-01-16 18:00 UTC, merged